# -- Number of replicas for the deployment.
replicaCount: 1

# -- Docker image details.
image:
  # -- Docker image repository.
  repository: nginxinc/nginx-unprivileged
  # -- Image pull policy.
  pullPolicy: Always
  # -- Image tag.
  tag: "alpine3.18"

# -- Secrets for pulling images from private repositories.
imagePullSecrets: []

# -- Overrides for chart and deployment names.
nameOverride: ""
fullnameOverride: ""

# -- Configuration for the service account.
serviceAccount:
  # -- Whether to create a service account.
  create: true
  # -- Automatically mount API credentials for the service account.
  automount: true
  # -- Annotations for the service account.
  annotations: {}
  # -- Name of the service account to use.
  name: ""

# -- Annotations for pods.
podAnnotations: {}

# -- Labels for pods.
podLabels: {}

# -- Security context for the entire pod.
podSecurityContext: {}

# -- Security context for containers.
securityContext:
  # -- Drop capabilities for the container.
  capabilities:
    drop:
    - ALL
  # -- Mount the root filesystem as read-only.
  readOnlyRootFilesystem: true
  # -- Run the container as a non-root user.
  runAsNonRoot: true
  # -- User ID for the container (nginx user is 101).
  runAsUser: 101
  # -- Group ID for the container (nginx group is 101).
  runAsGroup: 101
  # -- Disallow privilege escalation.
  allowPrivilegeEscalation: false

# -- Configuration for the Kubernetes service.
service:
  # -- Service type (e.g., ClusterIP).
  type: ClusterIP
  # -- Service port.
  port: 8080

# -- Configuration for Ingress resources.
ingress:
  # -- Enable or disable Ingress.
  enabled: false
  # -- Ingress class.
  className: ""
  # -- Annotations for Ingress.
  annotations: {}
  # -- Ingress hosts and paths.
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- TLS configuration for Ingress.
  tls: []

livenessProbe:
  # -- Enable or disable the liveness probe.
  enabled: false
  # -- Path for the liveness probe.
  path: /ready

readinessProbe:
  # -- Enable or disable the readiness probe.
  enabled: true
  # -- Path for the readiness probe.
  path: /

# -- Resource requests and limits for the pod.
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# -- Autoscaling configuration.
autoscaling:
  # -- Enable or disable autoscaling.
  enabled: true
  # -- Minimum and maximum replicas.
  minReplicas: 1
  maxReplicas: 5
  # -- Target CPU utilization percentage.
  targetCPUUtilizationPercentage: 80
  # -- Target memory utilization percentage.
  targetMemoryUtilizationPercentage: 80

# -- Additional volumes for the Deployment.
volumes:
  - name: nginx-config
    emptyDir: {}
  - name: nginx-cache
    emptyDir: {}
  - name: tmp
    emptyDir: {}

# -- Additional volume mounts for the Deployment.
volumeMounts:
  - name: nginx-config
    mountPath: /home/nginx
  - name: nginx-cache
    mountPath: /var/cache/nginx
  - name: tmp
    mountPath: /tmp

# -- Node selector for the pod.
nodeSelector: {}

# -- Tolerations for the pod.
tolerations: []

# -- Affinity rules for the pod.
affinity: {}
