name: Generate Helm documentation
on:
  - pull_request
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1.1.7
      with:
        git-push: true
        chart-search-root: ./charts
